### ISSUE TITLE
Wrong image in adding-pages

### ISSUE THREAD

**Issue by hvnsweeting** [phoenixframework/phoenix_guides#654] opened 2017-02-15 17:44 UTC
https://github.com/phoenixframework/phoenix_guides/blob/master/docs/adding_pages.md

This shown the IMG at bottom "from Frank"

Site shows "from Phoenix" http://www.phoenixframework.org/docs/adding-pages

```
<figure ng-show="data.images[0].image.length">
    <a href="https://files.readme.io/tXWKhaWATbuiAnIZLplM_hello-from-phoenix.png" class="block-display-image-parent block-display-image-size-smart ">
      <img ng-src="https://files.readme.io/tXWKhaWATbuiAnIZLplM_hello-from-phoenix.png" src="https://files.readme.io/tXWKhaWATbuiAnIZLplM_hello-from-phoenix.png">
    </a>
    <figcaption class="ng-binding">Hello World, from Phoenix!</figcaption>
  </figure>
```

**Comment by Ingramz** [comment] 2017-03-02 19:01
This is a duplicate of #645

**Comment by chrismccord** [comment] 2017-05-17 14:19
This will be fixed in the guides overhaul. Thanks!

**Closed by chrismccord** 2017-05-17 14:19 UTC
