### ISSUE TITLE
Update docs to use distillery instead of exrm

### ISSUE THREAD

**Issue by JanStevens** [phoenixframework/phoenix_guides#638] opened 2017-01-01 17:20 UTC
The guides use exrm which is deprecated in favour of Distillery.

Let's upgrade the guide to use Distillery

Reference: https://github.com/bitwalker/exrm#news

**Comment by niels** [comment] 2017-01-27 14:21
+1; but this is a duplicate of #575.

**Closed** 2017-09-06 20:38 UTC
