### ISSUE TITLE
Merge guides into phoenix repository

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix_guides#391] opened 2015-10-06 04:45 UTC
At ElixirConf, @lancehalvorsen, @scrogson and myself were discussing merging the phoenix guides with the core repository. I had a quick go at this a few weeks ago - the branch is available at https://github.com/Gazler/phoenix/tree/merge-guides and the commit at https://github.com/Gazler/phoenix/commit/525c1afa68a5a62b933d5d331518812436e77c89

The goal of this is to remove the dependency of readme.io and use ex_doc and hexdocs.pm - this should result in the pages being served much faster as well as being integrated with the documentation.

A couple issues I can think of off the top of my head are:
- ex_doc currently only permits one level of guides and uses the h1 tags inside the page as anchors. This means laying out the pages as we currently do is not possible.
- ex_doc uses the filename for display, so the files would need to be renamed.
- All of the links will need updating to use internal links to the correct guide page/module doc

**Comment by Gazler** [comment] 2015-10-06 04:50
![phoenix](https://cloud.githubusercontent.com/assets/477511/10300425/2404be00-6bee-11e5-858f-b31e050cb4ab.png)

**Comment by jeffkreeftmeijer** [comment] 2015-10-06 06:45
I’d love to help out getting the guides into the main repository. It might be wise to branch off `master` in the phoenix_guides repository to work on getting the guides ExDoc-ready in there, though.

By the way, I've applied 525c1afa68a5a62b933d5d331518812436e77c89 locally and `git clone`d the phoenix_guides repository into `/guides` in the Phoenix repository. Which makes it quite easy to work on the guides without having to actually merge them in for now. When everything's done, we'll need to `subtree` the guides in to the main repository like @Gazler did in 3857754c452788e2706a46ad1c96bfcdf8758b49.

**Comment by lancehalvorsen** [comment] 2015-10-06 17:38
@Gazler, thanks for creating this issue. This is definitely something we'd like to investigate. Having the docs and guides in near proximity, and with the same look and feel would be a really good thing. There are some things we'll need to consider, though. Do we want these to be in the same repo? Will guides commits tend to muddy the waters of the Phoenix code commit history? Will we be able to group the guides into categories the way we do now on readme.io? I'm sure there are more considerations as well.

Having this issue here will allow us to keep the conversation about whether and how we might accomplish this in the same place.

Thanks again for opening this issue!

**Comment by Gazler** [comment] 2015-10-06 21:43
@lancehalvorsen @jeffkreeftmeijer Good points.

Once we know what needs to be done I can edit the tasks into the first comment of the issue.

I think the question of including the guides in the core repository is up to the core team. There are a few options:

 * __Single repository__ - issues and pull requests for the framework go into the same repository
 * __Two repositories same source__ - issues and pull requests are separate for each repository. Docs repository can be merged into the core periodically.
 * __Two repositories separate sources__ - that is how things work at the moment. Doing this means that we need to work out a way of including the guides into the documentation.

**Comment by wsmoak** [comment] 2015-11-01 20:51
I've also been looking at this, (and didn't realize until the end that this issue was already open!)  I elected to work in a branch of phoenix_guides just because it's easier.

https://github.com/wsmoak/phoenix_guides/tree/ex_doc_initial has the top level files and a couple of the subdirectories converted, and the generated html is at http://wsmoak.net/phoenix/guides/ .

Both "Learning" and "Adding Pages" on the left-hand menu are good ones to look at.

I think I learned some of the same things as @Gazler... in general:

- I couldn't find a way to suppress the "API Reference", which isn't needed in phoenix_guides.  It's only a problem if the Guides are a separate project, otherwise the Phoenix Framework API Docs will be in that spot, and (I think...) you'd get links to the function/arity references for free.

- As I learned in [1], the files have to be renamed to the text you want to appear in the menu. Having spaces in the filenames isn't ideal. I added a suggestion to have ExDoc use the text of the first `<h1>` as the menu item.

- Sub-menus are achieved by adding h2 tags (`##` in Markdown).  That means the files currently in subdirectories (bonus_guides, deployment,) might need to be consolidated if you want the sub-menus to look the same. Unless there's a way to pull one Markdown file into another?

- ExDoc prepends "extra-" to the filename, which is visible in the URL for every page.  Possibly to avoid clashes and accidentally overwriting files?  Hopefully that is (or can be made) configurable.

Any further thoughts on whether to move the docs over to phoenix or keep them in phoenix_guides?  Could it be separate and pulled in as a git submodule so the files are in the right place when the phoenix docs are generated?

Once that decision is made, someone can do the initial restructuring, and then we can round up some volunteers to help with the rest. :)

[1] https://github.com/elixir-lang/ex_doc/issues/450

**Comment by wsmoak** [comment] 2015-11-01 23:30
Here's what it looks like with the Guides as a git sub-module of Phoenix:  https://github.com/wsmoak/phoenix/tree/ex_doc_initial

Note the 'docs' directory is a submodule pointed at a branch of my phoenix_guides fork.  This is defined in the `.gitmodules` dotfile.  Then in `mix.exs`, it's just the usual paths to the 'extra' pages.

It's published here:  http://wsmoak.net/phoenix/doc/  (click on Pages then pick one.)

However... using submodules was problematic in Subversion, and I imagine it's the same in Git.  Because the submodule points at a branch, like any other dependency it really needs to be locked down before the project is released.  That would mean the Guides have to be released *before* Phoenix is -- or at least the .gitmodules file must be edited to point at a to-be-created tag of the Guides -- otherwise you don't have a reproducible build from the tag on `phoenixframework/phoenix`.

So, what are the options?
- git subtree (requires separate commit into phoenix, duplicates content)
- git submodule (requires `git submodule update` & changing .gitmodules at release time)
- just move the files to phoenix and do everything there (loses contribution history on the files?)

Any other options we should consider?  Is it possible to release the Guides as a hex package and then pull them into Phoenix that way?  Assuming the point of this exercise is to combine the Guides with the Phoenix API docs, they just have to be *somewhere* so ex_doc can find them.

**Comment by wsmoak** [comment] 2015-11-04 02:23
So far I'm really happy with the "phoenix_guides as mix dependency" idea.  It keeps git out of the picture as far as subtrees or submodules, and it Just Works.

Here's the branch:  https://github.com/wsmoak/phoenix/tree/ex_doc_with_guides_as_dep 

All the changes are in mix.exs -- adding phoenix_guides as a dependency, currently pointed at a branch of my fork, and then using "deps/phoenix_guides/File Name.md" to pick them up.

If you clone it you'll need to change the ex_doc dependency back to a release -- I'm currently lobbying them to make the "extra-" prefix on all the filenames configurable and am using a local ex_doc with modifications.

Currently we're getting URLS like this:  http://wsmoak.net/phoenix/doc/extra-community.html

I want this:  http://wsmoak.net/phoenix/doc/community.html 

(one or the other may be 404 depending on what's published at the time.)

I could use some support over on elixir-lang-core if you feel the same way!  https://groups.google.com/forum/#!topic/elixir-lang-core/UzhyIhvQsC8

**Comment by Gazler** [comment] 2015-11-04 12:45
@wsmoak This is some great work. Thanks for updating all the page names. It looks like your guides may be missing some pages? Did you run in to the issue where there will be a lot of top level pages?

In terms of how we decide to bring the guides in to Phoenix, i'm just going to mention the way I initially thought this would work (with `git subtree`) as you have covered the way to use `submodule` and `deps` in quite some depth.

With `git subtree`, you can do `git subtree add --prefix=guides phoenix_guides/master` this will import the guides (with commit history) into the current project (preserving commit history.) Doing this has the benefit of allowing the checkout of an older commit and having the correct guides for that version. The `subtree` would only have to be used for the inital import.

I then imagined phoenix guides being a fork of the phoenix project designed for pull requests and issues relating to the guides (similar to [rails/docrails](http://weblog.rubyonrails.org/2012/3/7/what-is-docrails/) which seems to have been deleted today :disappointed:) This could be merged upstream periodically.

This allows keeping the guides and the codebase separate so that the right people can address and merge pull requests/issues, but combines them when building the docs.

So we currently have the following options:

 * `mix dep` - https://github.com/wsmoak/phoenix/tree/ex_doc_with_guides_as_dep
 * `submodule` - https://github.com/wsmoak/phoenix/tree/ex_doc_initial
 * `subtree` - https://github.com/Gazler/phoenix/tree/merge-guides

For me, the decision depends largely on how the people who deploy the docs want to keep the guides updated. Technically keeping them updated requires a similar amount of effort for all 3.

**Comment by wsmoak** [comment] 2015-11-07 15:23
We're still working on removing the "extras-" prefix over in ex_doc: https://github.com/elixir-lang/ex_doc/pull/462

Next I'd like to see it use the text of the first <h1> as the menu item so that we don't _have_ to rename the files "Upper Case With Spaces.md" only to see them converted back to upper-case-with-spaces.html.

The files are all going to be at the top level for now -- AIUI there's an issue with linking to the assets if the generated html files are in subdirectories.

The collapsible menus currently work from the <h2>'s in each file... meaning that to get one menu item for "Bonus Guides" with sub-menus for each of the topics, they would all have to be in one file.  I don't want to do that, so I'm thinking about how to concatenate the separate .md files at build time and only tell ex_doc about the combined one.

Let me know if you see anything else that needs to be considered!  José already pointed out that we'll eventually need a way to include images. :)

**Comment by Gazler** [comment] 2015-11-09 15:14
I like the solution at https://github.com/elixir-lang/ex_doc/pull/470 - it means we don't need to rename any files in the guides.

I think maybe concatenating the files could be a mix task? Maybe `mix guides.concat` could be run before `mix docs` in the phoenix application? We could then reference the concatenated files in the `mix.exs` extras for Phoenix. We can then define an alias that will run both mix tasks.

**Comment by milmazz** [comment] 2015-11-10 00:11
@Gazler elixir-lang/ex_doc#470 it's already in `master`. Please let me know if I can help with something else.

**Comment by wsmoak** [comment] 2015-11-11 13:23
It's looking good over there!  I just opened a PR for the last thing on my [current] list, for it to pick up the first `<h1>` as the menu title so we don't have to duplicate that text.  https://github.com/elixir-lang/ex_doc/pull/471

**Comment by wsmoak** [comment] 2015-11-18 00:25
I think all the changes are in ExDoc now -- we won't need to rename any files, just add a `#` line to the top of each one with the title, and that will get used in the menu.  (Or you can configure the menu item text if you want it to be different than the first `<h1>` in the file.

For the moment, all the extra files will be at the top level of the generated docs.  My current thought is... rather than concatenate the files, just keep it simple and let the menu be long for now.  Eventually someone will figure out how to get the links working in subdirectories.

So, someone needs to decide *how* to pull the guides into the main Phoenix repo.  I remain a fan of the mix dependency option, (the less git is involved, the better,) but whoever does the Phoenix releases needs to vote.

That decision controls *where* the files land, and thus, the configuration in mix.exs.

**Comment by stevedomin** [comment] 2015-11-20 22:39
:+1: on external mix package

In my opinion, if you are using submodule or subtree then you have to make sure the guides are always up to date with Phoenix at the time of creating a release (so that when people checkout a version they get the correct version of guides). I'm thinking this might slow down the release process.

Also having issues and PRs separated is probably a good thing as it's making things a little less messier.

**Comment by willykaram** [comment] 2015-12-27 00:59
I'd agree w/the mix package/dependency approach, as it would have less risk of impacting the core release cycle and allow for more flexibility for guides to evolve over time following release (which they naturally tend to do with many projects. Including images/videos in docs is an important consideration we shouldn't overlook if they are to be responsive (I have some experience with this and can assist if helpful).

**Comment by jeregrine** [comment] 2016-05-17 18:23
I'm all for moving off of readme.io but the questions are where/how/whome is this still something people are interested in?

**Comment by chrismccord** [comment] 2016-05-17 18:49
Soon, but it will need to wait until I'm ready to move on this, which I'm not quite there yet

**Comment by jeregrine** [comment] 2016-05-17 18:56
@chrismccord

**Comment by willykaram** [comment] 2016-05-17 19:29
@chrismccord once you're ready to move on this, I can dedicate some time to helping you, @lancehalvorsen and other with the move.

**Comment by Gazler** [comment] 2016-05-18 07:35
I'm still on board with this change, however readme.io seems a lot more reliable than when I first opened the issue. We have the following pages that probably won't work being embedded into the guides:

 * Landing page - https://phoenixframework.org
 * Blog - http://www.phoenixframework.org/blog

We could do something similar to the way the elixir site works for those potentially.

**Comment by Gazler** [comment] 2016-09-26 20:03
@wsmoak Great news! After months (nearly a year) of deliberation, it has been resolved that the dependency technique you outlined is the way to proceed with these guides.

Since you have pretty much done everything we need, it would be awesome if you could open up a PR with the guides as an Elixir application so that we can include it in Phoenix. If this is something that you don't have time for at the moment, that's cool too. Just wanted to make sure you had first chance since you've done all the work already!

**Comment by wsmoak** [comment] 2016-10-09 19:49
I missed this comment until someone pointed it out to me on Slack just now.  Give me a few days to refresh my memory on what I was doing here...

**Comment by wsmoak** [comment] 2016-10-10 00:32
... or a few hours. :)  Let me know what you think on https://github.com/phoenixframework/phoenix/pull/1960 .

**Comment by wsmoak** [comment] 2016-10-22 17:49
Update: @Gazler has re-arranged and renamed the files in here phoenix_guides (see the ex_doc branch) and there is a new mix.exs file that allows you to 'preview' by generating the html for all the *.md files under docs.  

It does not do the sub-menus, because that would mean duplicating all of the config that is already in the (proposed) phoenixframework/phoenix mix.exs (See https://github.com/phoenixframework/phoenix/pull/1960 )

Here is the latest preview http://wsmoak.net/phoenix/

Once phoenix_guides/ex_doc is "good enough" to be merged to master, it will be easier for people to contribute the rest of the fixes, such as changing the level of the h2/h3's to make the right things show up in the side menu, and other updates for changes in the Phoenix codebase.

I'm going to go ask on phoenix-core about the release process, because this is going to add a step to make sure Phoenix's mix.exs is pointed at the 'right' docs.

**Comment by willykaram** [comment] 2016-10-22 18:29
Thanks @wsmoak and @Gazler for moving this forward. As mentioned back in May, I'm available if there's to assist with this if possible, so please LMK if there's anything I can do to assist.

**Comment by wsmoak** [comment] 2016-10-23 22:46
You're welcome to jump in @willykaram .  If you're working on content at worst you may have to rebase and fix conflicts or copy it over, since as you can see on the branch, the files have been moved and renamed.

There isn't a task list, we're just figuring things out as we go. :)  

Today I was investigating how to publish the docs to see if there would be any changes to the release process, and to see how to update the docs for a release later if needed.  

(I also asked Eric about publishing 'nightly' or non-released docs on hexdocs, and learned that it's not currently allowed, but he asked me to open an issue to discuss:  https://github.com/hexpm/hex_web/issues/425 .)

**Comment by wsmoak** [comment] 2016-10-30 16:38
What's left to do before phoenix_guides/master can be 'switched over' to the new built-with-ex_doc docs?

I've done the infrastructure part, getting the mix.exs files to do what they need to do.

I assume this is targeted to happen before Phoenix 1.3 is released. It would be good to make the switch soon so that it's easier for others to contribute.

**Comment by Gazler** [comment] 2016-11-01 08:31
@wsmoak Is http://wsmoak.net/phoenix/overview.html the latest version?

I think the main thing is to go through the guides, checking the formatting and updating URLs so they no longer point to phoenixframework.org and link internally instead. I am happy to do this.

**Comment by wsmoak** [comment] 2016-11-02 02:14
I published the preview docs right before I commented, so it's fairly recent.

I agree the formatting and urls need to be fixed, but do we want to do that on the branch?  Other changes have already been merged into master so it just seems like that's asking for conflicts.  

Plus if it's on master then it's much easier for everyone else to help.  (Getting set up to build the docs from the branches isn't as easy.)

**Comment by Gazler** [comment] 2016-11-02 08:37
@wsmoak Great points, there is nothing preventing merging before changing the formatting. I have pushed up the changes in the `ex_doc` branch to master.

**Comment by wsmoak** [comment] 2016-11-03 00:32
Thanks for merging the changes into master, @Gazler .  Almost there!

I updated https://github.com/phoenixframework/phoenix/pull/1960 and asked for comments.

 http://wsmoak.net/phoenix/ is the latest (at  4ec8022 ).

**Comment by wsmoak** [comment] 2016-11-12 23:59
... and it's all merged on the Phoenix side, so `mix docs` in the phoenixframework/phoenix repo will build both the guides and the API docs.  (it defaults to MIX_ENV=docs, you don't need to include that.)

I think this one can be closed.

In summary, the guides were not merged as requested in the issue title, they are included as a mix dependency.  You can either build the guides + api docs from the phoenix repo, or just the guides from this one, so you can preview changes easily.

**Closed** 2016-11-18 08:42 UTC
Labels: enhancement, question
