### ISSUE TITLE
Replace references to mix phoenix.new with mix phx.new in Mix Tasks Guide

### ISSUE THREAD

**Issue by josephleniston** [phoenixframework/phoenix_guides#778] opened 2017-08-29 21:39 UTC
In the Mix Tasks Guide https://hexdocs.pm/phoenix/mix_tasks.html there are multiple references to

`mix phoenix.new`

However this has be superseded by `mix phx.new`. Especially in this section:

> We have seen all of these at one point or another in the guides, but having all the information about them in one place seems like a good idea. And here we are.

> `mix phoenix.new`

> This is how we tell Phoenix the framework to generate a new Phoenix application for us. We saw it early on in the Up and Running Guide.

This is now incorrect. The Up and Running Guide now has this:

> We can run `mix phx.new` from any directory in order to bootstrap our Phoenix application. Phoenix will accept either an absolute or relative path for the directory of our new project. Assuming that the name of our application is hello, let’s run the following command:

> `$ mix phx.new hello`

**Comment by jeregrine** [comment] 2017-09-06 17:40
Duplicate of 707

**Closed by jeregrine** 2017-09-06 17:40 UTC
Labels: enhancement, help wanted
